default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres

development:
  <<: *default
  database: everlywell_dev

test:
  <<: *default
  database: everlywell_test
